import { lazy } from 'react';

export const MessagesPage = lazy(() => import('@/components/MessagesPage'));
export const ServiceDetailPage = lazy(() => import('@/components/pages/ServiceDetail').then(m => ({ default: m.ServiceDetailPage })));
export const SellerProfilePage = lazy(() => import('@/components/pages/SellerProfile').then(m => ({ default: m.SellerProfilePage })));
export const RegisterPage = lazy(() => import('@/components/pages/UserPages').then(m => ({ default: m.RegisterPage })));
export const ProfilePage = lazy(() => import('@/components/pages/UserPages').then(m => ({ default: m.ProfilePage })));
export const SearchPage = lazy(() => import('@/components/pages/UserPages').then(m => ({ default: m.SearchPage })));
export const FavoritesPage = lazy(() => import('@/components/pages/UserPages').then(m => ({ default: m.FavoritesPage })));
export const RulesPage = lazy(() => import('@/components/pages/UserPages').then(m => ({ default: m.RulesPage })));
export const LoginPage = lazy(() => import('@/components/pages/LoginPage').then(m => ({ default: m.LoginPage })));
export const WorkPage = lazy(() => import('@/components/pages/work/WorkPage').then(m => ({ default: m.WorkPage })));
export const AdminPage = lazy(() => import('@/components/pages/admin/AdminPage').then(m => ({ default: m.AdminPage })));
export const ReferralPage = lazy(() => import('@/components/pages/referral/ReferralPage').then(m => ({ default: m.ReferralPage })));
export const CategoryProvidersPage = lazy(() => import('@/components/pages/category/CategoryProvidersPage').then(m => ({ default: m.CategoryProvidersPage })));
export const InvitationsPage = lazy(() => import('@/components/pages/invitations/InvitationsPage').then(m => ({ default: m.InvitationsPage })));
export const RafflePage = lazy(() => import('@/components/pages/RafflePage').then(m => ({ default: m.RafflePage })));
export const DatingPage = lazy(() => import('@/components/pages/DatingPage').then(m => ({ default: m.DatingPage })));
export const WalletPage = lazy(() => import('@/components/pages/WalletPage').then(m => ({ default: m.WalletPage })));
export const OnlineSearchPage = lazy(() => import('@/components/pages/OnlineSearchPage').then(m => ({ default: m.OnlineSearchPage })));
export const PartiesPage = lazy(() => import('@/components/parties/PartiesPage'));
export const PartyDetailPage = lazy(() => import('@/components/parties/PartyDetailPage'));
export const PartyChatPage = lazy(() => import('@/components/parties/PartyChatPage'));
export const OrganizerDashboard = lazy(() => import('@/components/parties/OrganizerDashboard'));
export const MyAdsPage = lazy(() => import('@/components/pages/my-ads/MyAdsPage'));
export const UserGuidePage = lazy(() => import('@/components/pages/UserGuidePage'));
export const BookingsPage = lazy(() => import('@/components/pages/BookingsPage').then(m => ({ default: m.BookingsPage })));
export const MyOrdersPage = lazy(() => import('@/components/pages/MyOrdersPage').then(m => ({ default: m.MyOrdersPage })));
export const OrderChatPage = lazy(() => import('@/components/pages/order-chat/OrderChatPage').then(m => ({ default: m.OrderChatPage })));
export const SwipePage = lazy(() => import('@/components/pages/SwipePage'));
export const MatchesPage = lazy(() => import('@/components/pages/MatchesPage'));
export const BusinessServicesPage = lazy(() => import('@/components/pages/BusinessServicesPage').then(m => ({ default: m.BusinessServicesPage })));