import { Page, Profile, CatalogItem, Review, UserRole, Wallet, Notification } from '@/types';

export interface AppPagesProps {
  currentPage: Page;
  setCurrentPage: (page: Page) => void;
  userRole: UserRole;
  setUserRole: (role: UserRole) => void;
  setIsAuthenticated?: (value: boolean) => void;
  profile: Profile;
  catalogItems: CatalogItem[];
  reviews: Review[];
  favorites: number[];
  toggleFavorite: (id: number) => void;
  selectedServiceId: number | null;
  setSelectedServiceId: (id: number | null) => void;
  setShowBookingModal: (show: boolean) => void;
  searchQuery: string;
  setSearchQuery: (query: string) => void;
  selectedCategory: string;
  setSelectedCategory: (category: string) => void;
  priceRange: string;
  setPriceRange: (range: string) => void;
  sortBy: string;
  setSortBy: (sort: string) => void;
  selectedCountry: string;
  setSelectedCountry: (country: string) => void;
  selectedLocation: string;
  setSelectedLocation: (location: string) => void;
  selectedAge: string;
  setSelectedAge: (age: string) => void;
  selectedHeight: string;
  setSelectedHeight: (height: string) => void;
  selectedBodyType: string;
  setSelectedBodyType: (bodyType: string) => void;
  selectedSellerId: number | null;
  setSelectedSellerId: (id: number | null) => void;
  onProfileUpdate?: (updatedProfile: Partial<Profile>) => void;
  wallet: Wallet;
  setWallet?: (wallet: Wallet) => void;
  walletTransactions?: any[];
  setWalletTransactions?: (transactions: any[]) => void;
  selectedPartyId?: number | null;
  setSelectedPartyId?: (id: number | null) => void;
  selectedApplicationId?: number | null;
  setSelectedApplicationId?: (id: number | null) => void;
  onNotificationAdd?: (notification: Notification) => void;
  addNotification?: (notification: Omit<Notification, 'id' | 'time' | 'read'>) => void;
  onOpenLovePurchase?: () => void;
  onPremiumRequired?: () => void;
  bookings: any[];
  setBookings: (bookings: any[]) => void;
  orderChats: any[];
  setOrderChats: (chats: any[]) => void;
  selectedOrderChatId: number | null;
  setSelectedOrderChatId: (id: number | null) => void;
}